export default {
  active: true,
  name: 'Objecture | Model',
  source: 'documents/model',
  target: 'localhost/model',
  ignore: [],
  main: 'index.html',
  pilers: {
    sans: [{
      name: 'ClearPiler',
      type: 'sans',
      target: 'source',
      path: ['**/template.js'],
      ignore: ['**/$template.js'],
    }, {
      name: 'ClearPiler',
      type: 'sans',
      target: 'target',
      path: ['*.{html,css,js,md,map,ico}'],
      ignore: [],
    }],
    simules: [{
      name: 'SimulePiler',
      type: 'simules',
      outputType: 'path',
      input: '../../../node_modules/core-plex/distributement/core-plex.js',
      output: '../../static/dependencies/core-plex.js',
      watch: ['../../../node_modules/core-plex/distributement/core-plex.js'],
      ignore: [],
    }, {
      name: 'SimulePiler',
      type: 'simules',
      outputType: 'path',
      input: '../../../node_modules/core-plex/distributement/core-plex.js.map',
      output: '../../static/dependencies/core-plex.js.map',
      watch: ['../../../node_modules/core-plex/distributement/core-plex.js.map'],
      ignore: [],
    }, {
      name: 'SimulePiler',
      type: 'simules',
      outputType: 'path',
      input: '../../../node_modules/core-plex/distributement/core-plex.min.js',
      output: '../../static/dependencies/core-plex.min.js',
      watch: ['../../../node_modules/core-plex/distributement/core-plex.min.js'],
      ignore: [],
    }, {
      name: 'SimulePiler',
      type: 'simules',
      outputType: 'path',
      input: '../../../node_modules/core-plex/distributement/core-plex.min.js.map',
      output: '../../static/dependencies/core-plex.min.js.map',
      watch: ['../../../node_modules/core-plex/distributement/core-plex.min.js.map'],
      ignore: [],
    }],
    styles: [{
      name: 'SASSPiler',
      type: 'styles',
      input: 'index.scss',
      output: 'index.css',
      watch: [
        '**/*.scss',
        '../coutil/**/*.scss',
      ],
      ignore: [],
      inputOptions: {},
      outputOptions: {
        sourceMap: true,
      },
    }],
    scripts: [{
      name: 'RollupPiler',
      type: 'scripts',
      watch: [
        '**/*.js',
        '../coutil/**/*.js',
        '../../static/dependencies',
      ],
      ignore: [
        '**/$route.js',
        '**/$document.js',
        '**/$socket.js',
      ],
      input: 'index.js',
      output: 'index.js',
      inputOptions: {
        logLevel: 'silent', 
        external: [
          '/dependencies/objecture.js',
          '/coutil/index.js',
        ],
      },
      outputOptions: {
        format: 'es',
        sourcemap: true,
      },
    }],
    structs: [{
      name: 'EJSPiler',
      type: 'structs',
      outputType: 'server',
      model: 'index.json',
      watch: ['**/*.{ejs,json}'],
      ignore: ['**/$*.ejs'],
      input: 'index.ejs',
      output: 'index.html',
      outputOptions: {
        localsName: '$model',
        root: ['templates'],
      },
    }, {
      name: 'EJSPiler',
      type: 'structs',
      outputType: 'client',
      watch: ['**/$*.ejs'],
      ignore: [],
      input: '**/*.ejs',
      output: '',
      outputOptions: {
        localsName: '$model',
        root: [''],
      }, 
    }],
  }
}